#![allow(dead_code)]
// IO_QSPI

// ==== BEGIN AUTO-GENERATED REGISTER OFFSETS (tools/gen_register_offsets.py) ====
// Generated from specs/RP2040.svd -- do not edit by hand.

pub const IO_QSPI_BASE:                             u32 = 0x4001_8000;

pub const IO_QSPI_GPIO_QSPI_SCLK_STATUS:            u32 = IO_QSPI_BASE + 0x0;
pub const IO_QSPI_GPIO_QSPI_SCLK_CTRL:              u32 = IO_QSPI_BASE + 0x4;
pub const IO_QSPI_GPIO_QSPI_SS_STATUS:              u32 = IO_QSPI_BASE + 0x8;
pub const IO_QSPI_GPIO_QSPI_SS_CTRL:                u32 = IO_QSPI_BASE + 0xC;
// GPIO_QSPI_SD0_STATUS..GPIO_QSPI_SD3_STATUS
pub fn IO_QSPI_GPIO_QSPI_SD_STATUS(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x10 + n * 0x8
}

// GPIO_QSPI_SD0_CTRL..GPIO_QSPI_SD3_CTRL
pub fn IO_QSPI_GPIO_QSPI_SD_CTRL(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x14 + n * 0x8
}

pub const IO_QSPI_INTR:                             u32 = IO_QSPI_BASE + 0x30;
// PROC0_INTE..PROC1_INTE
pub fn IO_QSPI_PROC_INTE(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x34 + n * 0xC
}

// PROC0_INTF..PROC1_INTF
pub fn IO_QSPI_PROC_INTF(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x38 + n * 0xC
}

// PROC0_INTS..PROC1_INTS
pub fn IO_QSPI_PROC_INTS(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x3C + n * 0xC
}

pub const IO_QSPI_DORMANT_WAKE_INTE:                u32 = IO_QSPI_BASE + 0x4C;
pub const IO_QSPI_DORMANT_WAKE_INTF:                u32 = IO_QSPI_BASE + 0x50;
pub const IO_QSPI_DORMANT_WAKE_INTS:                u32 = IO_QSPI_BASE + 0x54;
// ==== END AUTO-GENERATED REGISTER OFFSETS ====

// ==== BEGIN AUTO-GENERATED FIELD BIT RANGES (tools/gen_field_ranges.py) ====
// Generated from specs/RP2040.svd -- do not edit by hand.

// GPIO_QSPI_SCLK_STATUS, GPIO_QSPI_SS_STATUS, GPIO_QSPI_SD0_STATUS, GPIO_QSPI_SD1_STATUS, GPIO_QSPI_SD2_STATUS, GPIO_QSPI_SD3_STATUS
pub const IO_QSPI_GPIO_QSPI_STATUS_IRQTOPROC_BIT:   u32 = 26;
pub const IO_QSPI_GPIO_QSPI_STATUS_IRQFROMPAD_BIT:  u32 = 24;
pub const IO_QSPI_GPIO_QSPI_STATUS_INTOPERI_BIT:    u32 = 19;
pub const IO_QSPI_GPIO_QSPI_STATUS_INFROMPAD_BIT:   u32 = 17;
pub const IO_QSPI_GPIO_QSPI_STATUS_OETOPAD_BIT:     u32 = 13;
pub const IO_QSPI_GPIO_QSPI_STATUS_OEFROMPERI_BIT:  u32 = 12;
pub const IO_QSPI_GPIO_QSPI_STATUS_OUTTOPAD_BIT:    u32 = 9;
pub const IO_QSPI_GPIO_QSPI_STATUS_OUTFROMPERI_BIT: u32 = 8;

// GPIO_QSPI_SCLK_CTRL, GPIO_QSPI_SS_CTRL, GPIO_QSPI_SD0_CTRL, GPIO_QSPI_SD1_CTRL, GPIO_QSPI_SD2_CTRL, GPIO_QSPI_SD3_CTRL
pub const IO_QSPI_GPIO_QSPI_CTRL_IRQOVER_LOW:       u32 = 28;
pub const IO_QSPI_GPIO_QSPI_CTRL_IRQOVER_HIGH:      u32 = 29;
pub const IO_QSPI_GPIO_QSPI_CTRL_INOVER_LOW:        u32 = 16;
pub const IO_QSPI_GPIO_QSPI_CTRL_INOVER_HIGH:       u32 = 17;
pub const IO_QSPI_GPIO_QSPI_CTRL_OEOVER_LOW:        u32 = 12;
pub const IO_QSPI_GPIO_QSPI_CTRL_OEOVER_HIGH:       u32 = 13;
pub const IO_QSPI_GPIO_QSPI_CTRL_OUTOVER_LOW:       u32 = 8;
pub const IO_QSPI_GPIO_QSPI_CTRL_OUTOVER_HIGH:      u32 = 9;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_LOW:       u32 = 0;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_HIGH:      u32 = 4;

// INTR
pub const IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH_BIT: u32 = 23;
pub const IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH_BIT: u32 = 19;
pub const IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH_BIT: u32 = 15;
pub const IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH_BIT: u32 = 11;
pub const IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW_BIT:  u32 = 22;
pub const IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW_BIT:  u32 = 18;
pub const IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW_BIT:  u32 = 14;
pub const IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW_BIT:  u32 = 10;
pub const IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW_BIT: u32 = 20;
pub const IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW_BIT: u32 = 16;
pub const IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW_BIT: u32 = 12;
pub const IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW_BIT: u32 = 8;
pub const IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH_BIT:  u32 = 7;
pub const IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW_BIT:   u32 = 6;
pub const IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH_BIT: u32 = 5;
pub const IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW_BIT:  u32 = 4;
pub const IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW_BIT: u32 = 2;
pub const IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 0;

// PROC0_INTE, PROC1_INTE
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 6;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 2;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 0;

// PROC0_INTF, PROC1_INTF
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 6;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 2;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 0;

// PROC0_INTS, PROC1_INTS
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 6;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 2;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 0;

// DORMANT_WAKE_INTE
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 6;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 2;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 0;

// DORMANT_WAKE_INTF
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 6;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 2;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 0;

// DORMANT_WAKE_INTS
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 6;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 2;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 0;
// ==== END AUTO-GENERATED FIELD BIT RANGES ====

// ==== BEGIN AUTO-GENERATED ENUMERATED VALUES (tools/gen_enum_values.py) ====
// Generated from specs/RP2040.svd -- do not edit by hand.

// GPIO_QSPI_SCLK_CTRL..GPIO_QSPI_SD3_CTRL: IRQOVER
pub const IO_QSPI_GPIO_QSPI_CTRL_IRQOVER_NORMAL:    u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_CTRL_IRQOVER_INVERT:    u32 = 0x1;
pub const IO_QSPI_GPIO_QSPI_CTRL_IRQOVER_LOW_1:     u32 = 0x2;
pub const IO_QSPI_GPIO_QSPI_CTRL_IRQOVER_HIGH_1:    u32 = 0x3;

// GPIO_QSPI_SCLK_CTRL..GPIO_QSPI_SD3_CTRL: INOVER
pub const IO_QSPI_GPIO_QSPI_CTRL_INOVER_NORMAL:     u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_CTRL_INOVER_INVERT:     u32 = 0x1;
pub const IO_QSPI_GPIO_QSPI_CTRL_INOVER_LOW_1:      u32 = 0x2;
pub const IO_QSPI_GPIO_QSPI_CTRL_INOVER_HIGH_1:     u32 = 0x3;

// GPIO_QSPI_SCLK_CTRL..GPIO_QSPI_SD3_CTRL: OEOVER
pub const IO_QSPI_GPIO_QSPI_CTRL_OEOVER_NORMAL:     u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_CTRL_OEOVER_INVERT:     u32 = 0x1;
pub const IO_QSPI_GPIO_QSPI_CTRL_OEOVER_DISABLE:    u32 = 0x2;
pub const IO_QSPI_GPIO_QSPI_CTRL_OEOVER_ENABLE:     u32 = 0x3;

// GPIO_QSPI_SCLK_CTRL..GPIO_QSPI_SD3_CTRL: OUTOVER
pub const IO_QSPI_GPIO_QSPI_CTRL_OUTOVER_NORMAL:    u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_CTRL_OUTOVER_INVERT:    u32 = 0x1;
pub const IO_QSPI_GPIO_QSPI_CTRL_OUTOVER_LOW_1:     u32 = 0x2;
pub const IO_QSPI_GPIO_QSPI_CTRL_OUTOVER_HIGH_1:    u32 = 0x3;

// GPIO_QSPI_SCLK_CTRL..GPIO_QSPI_SD3_CTRL: FUNCSEL
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_XIP_SCLK:  u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_SIO_30:    u32 = 0x5;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_NULL:      u32 = 0x1F;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_XIP_SS_N:  u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_SIO_31:    u32 = 0x5;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_XIP_SD0:   u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_SIO_32:    u32 = 0x5;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_XIP_SD1:   u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_SIO_33:    u32 = 0x5;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_XIP_SD2:   u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_SIO_34:    u32 = 0x5;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_XIP_SD3:   u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_CTRL_FUNCSEL_SIO_35:    u32 = 0x5;
// ==== END AUTO-GENERATED ENUMERATED VALUES ====
