#![allow(dead_code)]
// USB_DEVICE_DPRAM

// ==== BEGIN AUTO-GENERATED REGISTER OFFSETS (tools/gen_register_offsets.py) ====
// Generated from specs/RP2040.svd -- do not edit by hand.

pub const USB_DEVICE_DPRAM_BASE:                    u32 = 0x5010_0000;

pub const USB_DEVICE_DPRAM_SETUP_PACKET_LOW:        u32 = USB_DEVICE_DPRAM_BASE + 0x0;
pub const USB_DEVICE_DPRAM_SETUP_PACKET_HIGH:       u32 = USB_DEVICE_DPRAM_BASE + 0x4;
pub const USB_DEVICE_DPRAM_EP1_IN_CONTROL:          u32 = USB_DEVICE_DPRAM_BASE + 0x8;
pub const USB_DEVICE_DPRAM_EP2_IN_CONTROL:          u32 = USB_DEVICE_DPRAM_BASE + 0x10;
pub const USB_DEVICE_DPRAM_EP3_IN_CONTROL:          u32 = USB_DEVICE_DPRAM_BASE + 0x18;
pub const USB_DEVICE_DPRAM_EP4_IN_CONTROL:          u32 = USB_DEVICE_DPRAM_BASE + 0x20;
pub const USB_DEVICE_DPRAM_EP5_IN_CONTROL:          u32 = USB_DEVICE_DPRAM_BASE + 0x28;
pub const USB_DEVICE_DPRAM_EP6_IN_CONTROL:          u32 = USB_DEVICE_DPRAM_BASE + 0x30;
pub const USB_DEVICE_DPRAM_EP7_IN_CONTROL:          u32 = USB_DEVICE_DPRAM_BASE + 0x38;
pub const USB_DEVICE_DPRAM_EP8_IN_CONTROL:          u32 = USB_DEVICE_DPRAM_BASE + 0x40;
pub const USB_DEVICE_DPRAM_EP9_IN_CONTROL:          u32 = USB_DEVICE_DPRAM_BASE + 0x48;
pub const USB_DEVICE_DPRAM_EP10_IN_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x50;
pub const USB_DEVICE_DPRAM_EP11_IN_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x58;
pub const USB_DEVICE_DPRAM_EP12_IN_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x60;
pub const USB_DEVICE_DPRAM_EP13_IN_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x68;
pub const USB_DEVICE_DPRAM_EP14_IN_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x70;
pub const USB_DEVICE_DPRAM_EP15_IN_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x78;
pub const USB_DEVICE_DPRAM_EP1_OUT_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0xC;
pub const USB_DEVICE_DPRAM_EP2_OUT_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x14;
pub const USB_DEVICE_DPRAM_EP3_OUT_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x1C;
pub const USB_DEVICE_DPRAM_EP4_OUT_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x24;
pub const USB_DEVICE_DPRAM_EP5_OUT_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x2C;
pub const USB_DEVICE_DPRAM_EP6_OUT_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x34;
pub const USB_DEVICE_DPRAM_EP7_OUT_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x3C;
pub const USB_DEVICE_DPRAM_EP8_OUT_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x44;
pub const USB_DEVICE_DPRAM_EP9_OUT_CONTROL:         u32 = USB_DEVICE_DPRAM_BASE + 0x4C;
pub const USB_DEVICE_DPRAM_EP10_OUT_CONTROL:        u32 = USB_DEVICE_DPRAM_BASE + 0x54;
pub const USB_DEVICE_DPRAM_EP11_OUT_CONTROL:        u32 = USB_DEVICE_DPRAM_BASE + 0x5C;
pub const USB_DEVICE_DPRAM_EP12_OUT_CONTROL:        u32 = USB_DEVICE_DPRAM_BASE + 0x64;
pub const USB_DEVICE_DPRAM_EP13_OUT_CONTROL:        u32 = USB_DEVICE_DPRAM_BASE + 0x6C;
pub const USB_DEVICE_DPRAM_EP14_OUT_CONTROL:        u32 = USB_DEVICE_DPRAM_BASE + 0x74;
pub const USB_DEVICE_DPRAM_EP15_OUT_CONTROL:        u32 = USB_DEVICE_DPRAM_BASE + 0x7C;
// EP0_IN_BUFFER_CONTROL..EP15_IN_BUFFER_CONTROL
pub fn USB_DEVICE_DPRAM_EP_IN_BUFFER_CONTROL(ep: u32) -> u32 {
    return USB_DEVICE_DPRAM_BASE + 0x80 + ep * 0x8
}

// EP0_OUT_BUFFER_CONTROL..EP15_OUT_BUFFER_CONTROL
pub fn USB_DEVICE_DPRAM_EP_OUT_BUFFER_CONTROL(ep: u32) -> u32 {
    return USB_DEVICE_DPRAM_BASE + 0x84 + ep * 0x8
}
// ==== END AUTO-GENERATED REGISTER OFFSETS ====

// ==== BEGIN AUTO-GENERATED FIELD BIT RANGES (tools/gen_field_ranges.py) ====
// Generated from specs/RP2040.svd -- do not edit by hand.

// SETUP_PACKET_LOW
pub const USB_DEVICE_DPRAM_SETUP_PACKET_LOW_WVALUE_LOW:u32 = 16;
pub const USB_DEVICE_DPRAM_SETUP_PACKET_LOW_WVALUE_HIGH:u32 = 31;
pub const USB_DEVICE_DPRAM_SETUP_PACKET_LOW_BREQUEST_LOW:u32 = 8;
pub const USB_DEVICE_DPRAM_SETUP_PACKET_LOW_BREQUEST_HIGH:u32 = 15;
pub const USB_DEVICE_DPRAM_SETUP_PACKET_LOW_BMREQUESTTYPE_LOW:u32 = 0;
pub const USB_DEVICE_DPRAM_SETUP_PACKET_LOW_BMREQUESTTYPE_HIGH:u32 = 7;

// SETUP_PACKET_HIGH
pub const USB_DEVICE_DPRAM_SETUP_PACKET_HIGH_WLENGTH_LOW:u32 = 16;
pub const USB_DEVICE_DPRAM_SETUP_PACKET_HIGH_WLENGTH_HIGH:u32 = 31;
pub const USB_DEVICE_DPRAM_SETUP_PACKET_HIGH_WINDEX_LOW:u32 = 0;
pub const USB_DEVICE_DPRAM_SETUP_PACKET_HIGH_WINDEX_HIGH:u32 = 15;

// EP1_IN_CONTROL..EP15_OUT_CONTROL
pub const USB_DEVICE_DPRAM_EP_CONTROL_ENABLE_BIT:   u32 = 31;
pub const USB_DEVICE_DPRAM_EP_CONTROL_DOUBLE_BUFFERED_BIT:u32 = 30;
pub const USB_DEVICE_DPRAM_EP_CONTROL_INTERRUPT_PER_BUFF_BIT:u32 = 29;
pub const USB_DEVICE_DPRAM_EP_CONTROL_INTERRUPT_PER_DOUBLE_BUFF_BIT:u32 = 28;
pub const USB_DEVICE_DPRAM_EP_CONTROL_ENDPOINT_TYPE_LOW:u32 = 26;
pub const USB_DEVICE_DPRAM_EP_CONTROL_ENDPOINT_TYPE_HIGH:u32 = 27;
pub const USB_DEVICE_DPRAM_EP_CONTROL_INTERRUPT_ON_STALL_BIT:u32 = 17;
pub const USB_DEVICE_DPRAM_EP_CONTROL_INTERRUPT_ON_NAK_BIT:u32 = 16;
pub const USB_DEVICE_DPRAM_EP_CONTROL_BUFFER_ADDRESS_LOW:u32 = 0;
pub const USB_DEVICE_DPRAM_EP_CONTROL_BUFFER_ADDRESS_HIGH:u32 = 15;

// EP0_IN_BUFFER_CONTROL..EP15_OUT_BUFFER_CONTROL
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_FULL_1_BIT:u32 = 31;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_FULL_0_BIT:u32 = 15;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_LAST_1_BIT:u32 = 30;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_LAST_0_BIT:u32 = 14;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_PID_1_BIT:u32 = 29;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_PID_0_BIT:u32 = 13;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_LOW:u32 = 27;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_HIGH:u32 = 28;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_AVAILABLE_1_BIT:u32 = 26;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_AVAILABLE_0_BIT:u32 = 10;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_LENGTH_1_LOW:u32 = 16;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_LENGTH_1_HIGH:u32 = 25;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_LENGTH_0_LOW:u32 = 0;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_LENGTH_0_HIGH:u32 = 9;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_RESET_BIT:u32 = 12;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_STALL_BIT:u32 = 11;
// ==== END AUTO-GENERATED FIELD BIT RANGES ====

// ==== BEGIN AUTO-GENERATED ENUMERATED VALUES (tools/gen_enum_values.py) ====
// Generated from specs/RP2040.svd -- do not edit by hand.

// EP1_IN_CONTROL..EP15_OUT_CONTROL: ENDPOINT_TYPE
pub const USB_DEVICE_DPRAM_EP_CONTROL_ENDPOINT_TYPE_CONTROL:u32 = 0x0;
pub const USB_DEVICE_DPRAM_EP_CONTROL_ENDPOINT_TYPE_ISOCHRONOUS:u32 = 0x1;
pub const USB_DEVICE_DPRAM_EP_CONTROL_ENDPOINT_TYPE_BULK:u32 = 0x2;
pub const USB_DEVICE_DPRAM_EP_CONTROL_ENDPOINT_TYPE_INTERRUPT:u32 = 0x3;

// EP0_IN_BUFFER_CONTROL..EP15_OUT_BUFFER_CONTROL: DOUBLE_BUFFER_ISO_OFFSET
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_128:u32 = 0x0;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_256:u32 = 0x1;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_512:u32 = 0x2;
pub const USB_DEVICE_DPRAM_EP_BUFFER_CONTROL_DOUBLE_BUFFER_ISO_OFFSET_1024:u32 = 0x3;
// ==== END AUTO-GENERATED ENUMERATED VALUES ====
