// Pin capabilities of the RP2350 GPIO driver.
// Source: RP2350 datasheet, "GPIO function table" (F5 = SIO).
// Bank 0 GPIO0..GPIO47 can all be used as plain software GPIO;
// GPIO30..GPIO47 only exist on the QFN-80 (RP2350B) package.

use crate::HAL::Pin::PinCapability;
use crate::HAL::Pin::PinFunction;

pub static PIN_CAPABILITIES: &[PinCapability] = &[
    PinCapability { pin:  0, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin:  1, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin:  2, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin:  3, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin:  4, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin:  5, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin:  6, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin:  7, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin:  8, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin:  9, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 10, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 11, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 12, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 13, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 14, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 15, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 16, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 17, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 18, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 19, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 20, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 21, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 22, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 23, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 24, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 25, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 26, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 27, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 28, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 29, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 30, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 31, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 32, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 33, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 34, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 35, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 36, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 37, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 38, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 39, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 40, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 41, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 42, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 43, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 44, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 45, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 46, function: PinFunction::GPIO, peripheralBlock: 0 },
    PinCapability { pin: 47, function: PinFunction::GPIO, peripheralBlock: 0 },
];
