use crate::Util::Register::Register;
use crate::Util::LowLevel::_poll;
use crate::Kernel::Drivers::TimerDriver::TimerDriver;

use crate::Native::Constants::RP2040::RESETS::*;
use crate::Native::Constants::RP2040::TIMER::*;
use crate::Native::Constants::RP2040::WATCHDOG::*;

pub struct _TimerDriver {
    timehr : Register,
    timelr : Register,

    // The tick generator behind the 1us reference lives in the WATCHDOG block.
    // It is owned by this driver and deliberately not exposed any further.
    watchdogTick : Register,
}

impl TimerDriver for _TimerDriver {
    fn nowTick(&self) -> u64 {
        let low = self.timelr.read();
        let high = self.timehr.read();
        // Combine high bits and low bits
        return ((high as u64) << 32) | (low as u64);
    }

    /// RP2040 quirk: the TIMER has no clock of its own - its microseconds are
    /// generated by the watchdog tick generator, which divides clk_ref down to
    /// 1us (datasheet 4.6 + 4.7.2). When the chip is reset by a debugger
    /// instead of by the bootrom, nobody else brings this up.
    fn init(&self, refFreq: u32) -> bool {
        // `refFreq` is the clk_ref frequency: the tick generator divides clk_ref
        // down to the 1us reference. Never feed it the CPU/PLL clock - that
        // scales every delay by clk_sys/clk_ref (~10x at 125MHz vs 12MHz).
        // (Truncating division: a 6.5MHz ROSC reference is ~8% off, which is
        // unavoidable since the divider is an integer.)
        self.watchdogTick.fieldSet(WATCHDOG_TICK_CYCLES_HIGH,
                                   WATCHDOG_TICK_CYCLES_LOW,
                                   refFreq / 1_000_000);

        // Configure watchdog first
        self.watchdogTick.bitSet(WATCHDOG_TICK_ENABLE_BIT, true);
        if !_poll(100_000, || self.watchdogTick.bitGet(WATCHDOG_TICK_RUNNING_BIT)) {
            return false;
        }

        // Give the timer a reset pulse *after* the tick is live
        // Otherwise the timer will not notice watchdog
        let reset = Register::new(RESETS_RESET);
        let resetDone = Register::new(RESETS_RESET_DONE);
        reset.bitSet(RESETS_RESET_TIMER_BIT, true);
        reset.bitSet(RESETS_RESET_TIMER_BIT, false);
        if !_poll(100_000, || resetDone.bitGet(RESETS_RESET_DONE_TIMER_BIT)) {
            return false;
        }

        // Clear PAUSE / DBGPAUSE *after* the reset pulse
        // the watchdog will continue to run under debugger
        let timerPause = Register::new(TIMER_PAUSE);
        let timerDbgPause = Register::new(TIMER_DBGPAUSE);
        // Resume hardware timer
        timerPause.write(0);
        // TIMER_DBGPAUSE_DBG0_BIT: pause watchdong when core0 is in debug mode
        // TIMER_DBGPAUSE_DBG1_BIT: ... when core1 is in debug mode
        timerDbgPause.write(0);
        if timerDbgPause.read() != 0 {
            return false;
        }

        // Finally prove the counter actually counts
        return _poll(100_000, || self.nowTick() != 0);
    }
}

impl _TimerDriver {
    pub fn new() -> Self {
        Self {
            timehr : Register::new(TIMER_TIMEHR),
            timelr : Register::new(TIMER_TIMELR),
            watchdogTick : Register::new(WATCHDOG_TICK),
        }
    }
}