#![allow(dead_code)]
// BUSCTRL

// ==== BEGIN AUTO-GENERATED REGISTER OFFSETS (tools/gen_register_offsets.py) ====
// Generated from specs/RP2350.svd -- do not edit by hand.

pub const BUSCTRL_BASE:                             u32 = 0x4006_8000;

pub const BUSCTRL_BUS_PRIORITY:                     u32 = BUSCTRL_BASE + 0x0;
pub const BUSCTRL_BUS_PRIORITY_ACK:                 u32 = BUSCTRL_BASE + 0x4;
pub const BUSCTRL_PERFCTR_EN:                       u32 = BUSCTRL_BASE + 0x8;
// PERFCTR0..PERFCTR3
pub fn BUSCTRL_PERFCTR(n: u32) -> u32 {
    return BUSCTRL_BASE + 0xC + n * 0x8
}

// PERFSEL0..PERFSEL3
pub fn BUSCTRL_PERFSEL(n: u32) -> u32 {
    return BUSCTRL_BASE + 0x10 + n * 0x8
}
// ==== END AUTO-GENERATED REGISTER OFFSETS ====

// ==== BEGIN AUTO-GENERATED FIELD BIT RANGES (tools/gen_field_ranges.py) ====
// Generated from specs/RP2350.svd -- do not edit by hand.

// BUS_PRIORITY
pub const BUSCTRL_BUS_PRIORITY_DMA_W_BIT:           u32 = 12;
pub const BUSCTRL_BUS_PRIORITY_DMA_R_BIT:           u32 = 8;
pub const BUSCTRL_BUS_PRIORITY_PROC1_BIT:           u32 = 4;
pub const BUSCTRL_BUS_PRIORITY_PROC0_BIT:           u32 = 0;

// BUS_PRIORITY_ACK
pub const BUSCTRL_BUS_PRIORITY_ACK_BIT:             u32 = 0;

// PERFCTR_EN
pub const BUSCTRL_PERFCTR_EN_BIT:                   u32 = 0;

// PERFCTR0, PERFCTR1, PERFCTR2, PERFCTR3
pub const BUSCTRL_PERFCTR_LOW:                      u32 = 0;
pub const BUSCTRL_PERFCTR_HIGH:                     u32 = 23;

// PERFSEL0, PERFSEL1, PERFSEL2, PERFSEL3
pub const BUSCTRL_PERFSEL_LOW:                      u32 = 0;
pub const BUSCTRL_PERFSEL_HIGH:                     u32 = 6;
// ==== END AUTO-GENERATED FIELD BIT RANGES ====

// ==== BEGIN AUTO-GENERATED ENUMERATED VALUES (tools/gen_enum_values.py) ====
// Generated from specs/RP2350.svd -- do not edit by hand.

// PERFSEL0..PERFSEL3: PERFSEL
pub const BUSCTRL_PERFSEL_SIOB_PROC1_STALL_UPSTREAM:u32 = 0x0;
pub const BUSCTRL_PERFSEL_SIOB_PROC1_STALL_DOWNSTREAM:u32 = 0x1;
pub const BUSCTRL_PERFSEL_SIOB_PROC1_ACCESS_CONTESTED:u32 = 0x2;
pub const BUSCTRL_PERFSEL_SIOB_PROC1_ACCESS:        u32 = 0x3;
pub const BUSCTRL_PERFSEL_SIOB_PROC0_STALL_UPSTREAM:u32 = 0x4;
pub const BUSCTRL_PERFSEL_SIOB_PROC0_STALL_DOWNSTREAM:u32 = 0x5;
pub const BUSCTRL_PERFSEL_SIOB_PROC0_ACCESS_CONTESTED:u32 = 0x6;
pub const BUSCTRL_PERFSEL_SIOB_PROC0_ACCESS:        u32 = 0x7;
pub const BUSCTRL_PERFSEL_APB_STALL_UPSTREAM:       u32 = 0x8;
pub const BUSCTRL_PERFSEL_APB_STALL_DOWNSTREAM:     u32 = 0x9;
pub const BUSCTRL_PERFSEL_APB_ACCESS_CONTESTED:     u32 = 0xA;
pub const BUSCTRL_PERFSEL_APB_ACCESS:               u32 = 0xB;
pub const BUSCTRL_PERFSEL_FASTPERI_STALL_UPSTREAM:  u32 = 0xC;
pub const BUSCTRL_PERFSEL_FASTPERI_STALL_DOWNSTREAM:u32 = 0xD;
pub const BUSCTRL_PERFSEL_FASTPERI_ACCESS_CONTESTED:u32 = 0xE;
pub const BUSCTRL_PERFSEL_FASTPERI_ACCESS:          u32 = 0xF;
pub const BUSCTRL_PERFSEL_SRAM9_STALL_UPSTREAM:     u32 = 0x10;
pub const BUSCTRL_PERFSEL_SRAM9_STALL_DOWNSTREAM:   u32 = 0x11;
pub const BUSCTRL_PERFSEL_SRAM9_ACCESS_CONTESTED:   u32 = 0x12;
pub const BUSCTRL_PERFSEL_SRAM9_ACCESS:             u32 = 0x13;
pub const BUSCTRL_PERFSEL_SRAM8_STALL_UPSTREAM:     u32 = 0x14;
pub const BUSCTRL_PERFSEL_SRAM8_STALL_DOWNSTREAM:   u32 = 0x15;
pub const BUSCTRL_PERFSEL_SRAM8_ACCESS_CONTESTED:   u32 = 0x16;
pub const BUSCTRL_PERFSEL_SRAM8_ACCESS:             u32 = 0x17;
pub const BUSCTRL_PERFSEL_SRAM7_STALL_UPSTREAM:     u32 = 0x18;
pub const BUSCTRL_PERFSEL_SRAM7_STALL_DOWNSTREAM:   u32 = 0x19;
pub const BUSCTRL_PERFSEL_SRAM7_ACCESS_CONTESTED:   u32 = 0x1A;
pub const BUSCTRL_PERFSEL_SRAM7_ACCESS:             u32 = 0x1B;
pub const BUSCTRL_PERFSEL_SRAM6_STALL_UPSTREAM:     u32 = 0x1C;
pub const BUSCTRL_PERFSEL_SRAM6_STALL_DOWNSTREAM:   u32 = 0x1D;
pub const BUSCTRL_PERFSEL_SRAM6_ACCESS_CONTESTED:   u32 = 0x1E;
pub const BUSCTRL_PERFSEL_SRAM6_ACCESS:             u32 = 0x1F;
pub const BUSCTRL_PERFSEL_SRAM5_STALL_UPSTREAM:     u32 = 0x20;
pub const BUSCTRL_PERFSEL_SRAM5_STALL_DOWNSTREAM:   u32 = 0x21;
pub const BUSCTRL_PERFSEL_SRAM5_ACCESS_CONTESTED:   u32 = 0x22;
pub const BUSCTRL_PERFSEL_SRAM5_ACCESS:             u32 = 0x23;
pub const BUSCTRL_PERFSEL_SRAM4_STALL_UPSTREAM:     u32 = 0x24;
pub const BUSCTRL_PERFSEL_SRAM4_STALL_DOWNSTREAM:   u32 = 0x25;
pub const BUSCTRL_PERFSEL_SRAM4_ACCESS_CONTESTED:   u32 = 0x26;
pub const BUSCTRL_PERFSEL_SRAM4_ACCESS:             u32 = 0x27;
pub const BUSCTRL_PERFSEL_SRAM3_STALL_UPSTREAM:     u32 = 0x28;
pub const BUSCTRL_PERFSEL_SRAM3_STALL_DOWNSTREAM:   u32 = 0x29;
pub const BUSCTRL_PERFSEL_SRAM3_ACCESS_CONTESTED:   u32 = 0x2A;
pub const BUSCTRL_PERFSEL_SRAM3_ACCESS:             u32 = 0x2B;
pub const BUSCTRL_PERFSEL_SRAM2_STALL_UPSTREAM:     u32 = 0x2C;
pub const BUSCTRL_PERFSEL_SRAM2_STALL_DOWNSTREAM:   u32 = 0x2D;
pub const BUSCTRL_PERFSEL_SRAM2_ACCESS_CONTESTED:   u32 = 0x2E;
pub const BUSCTRL_PERFSEL_SRAM2_ACCESS:             u32 = 0x2F;
pub const BUSCTRL_PERFSEL_SRAM1_STALL_UPSTREAM:     u32 = 0x30;
pub const BUSCTRL_PERFSEL_SRAM1_STALL_DOWNSTREAM:   u32 = 0x31;
pub const BUSCTRL_PERFSEL_SRAM1_ACCESS_CONTESTED:   u32 = 0x32;
pub const BUSCTRL_PERFSEL_SRAM1_ACCESS:             u32 = 0x33;
pub const BUSCTRL_PERFSEL_SRAM0_STALL_UPSTREAM:     u32 = 0x34;
pub const BUSCTRL_PERFSEL_SRAM0_STALL_DOWNSTREAM:   u32 = 0x35;
pub const BUSCTRL_PERFSEL_SRAM0_ACCESS_CONTESTED:   u32 = 0x36;
pub const BUSCTRL_PERFSEL_SRAM0_ACCESS:             u32 = 0x37;
pub const BUSCTRL_PERFSEL_XIP_MAIN1_STALL_UPSTREAM: u32 = 0x38;
pub const BUSCTRL_PERFSEL_XIP_MAIN1_STALL_DOWNSTREAM:u32 = 0x39;
pub const BUSCTRL_PERFSEL_XIP_MAIN1_ACCESS_CONTESTED:u32 = 0x3A;
pub const BUSCTRL_PERFSEL_XIP_MAIN1_ACCESS:         u32 = 0x3B;
pub const BUSCTRL_PERFSEL_XIP_MAIN0_STALL_UPSTREAM: u32 = 0x3C;
pub const BUSCTRL_PERFSEL_XIP_MAIN0_STALL_DOWNSTREAM:u32 = 0x3D;
pub const BUSCTRL_PERFSEL_XIP_MAIN0_ACCESS_CONTESTED:u32 = 0x3E;
pub const BUSCTRL_PERFSEL_XIP_MAIN0_ACCESS:         u32 = 0x3F;
pub const BUSCTRL_PERFSEL_ROM_STALL_UPSTREAM:       u32 = 0x40;
pub const BUSCTRL_PERFSEL_ROM_STALL_DOWNSTREAM:     u32 = 0x41;
pub const BUSCTRL_PERFSEL_ROM_ACCESS_CONTESTED:     u32 = 0x42;
pub const BUSCTRL_PERFSEL_ROM_ACCESS:               u32 = 0x43;
// ==== END AUTO-GENERATED ENUMERATED VALUES ====
