#![allow(dead_code)]
// IO_QSPI

// ==== BEGIN AUTO-GENERATED REGISTER OFFSETS (tools/gen_register_offsets.py) ====
// Generated from specs/RP2350.svd -- do not edit by hand.

pub const IO_QSPI_BASE:                             u32 = 0x4003_0000;

pub const IO_QSPI_USBPHY_DP_STATUS:                 u32 = IO_QSPI_BASE + 0x0;
pub const IO_QSPI_USBPHY_DP_CTRL:                   u32 = IO_QSPI_BASE + 0x4;
pub const IO_QSPI_USBPHY_DM_STATUS:                 u32 = IO_QSPI_BASE + 0x8;
pub const IO_QSPI_USBPHY_DM_CTRL:                   u32 = IO_QSPI_BASE + 0xC;
pub const IO_QSPI_GPIO_QSPI_SCLK_STATUS:            u32 = IO_QSPI_BASE + 0x10;
pub const IO_QSPI_GPIO_QSPI_SCLK_CTRL:              u32 = IO_QSPI_BASE + 0x14;
pub const IO_QSPI_GPIO_QSPI_SS_STATUS:              u32 = IO_QSPI_BASE + 0x18;
pub const IO_QSPI_GPIO_QSPI_SS_CTRL:                u32 = IO_QSPI_BASE + 0x1C;
// GPIO_QSPI_SD0_STATUS..GPIO_QSPI_SD3_STATUS
pub fn IO_QSPI_GPIO_QSPI_SD_STATUS(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x20 + n * 0x8
}

// GPIO_QSPI_SD0_CTRL..GPIO_QSPI_SD3_CTRL
pub fn IO_QSPI_GPIO_QSPI_SD_CTRL(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x24 + n * 0x8
}

// IRQSUMMARY_PROC0_SECURE..IRQSUMMARY_PROC1_SECURE
pub fn IO_QSPI_IRQSUMMARY_PROC_SECURE(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x200 + n * 0x8
}

// IRQSUMMARY_PROC0_NONSECURE..IRQSUMMARY_PROC1_NONSECURE
pub fn IO_QSPI_IRQSUMMARY_PROC_NONSECURE(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x204 + n * 0x8
}

pub const IO_QSPI_IRQSUMMARY_DORMANT_WAKE_SECURE:   u32 = IO_QSPI_BASE + 0x210;
pub const IO_QSPI_IRQSUMMARY_DORMANT_WAKE_NONSECURE:u32 = IO_QSPI_BASE + 0x214;
pub const IO_QSPI_INTR:                             u32 = IO_QSPI_BASE + 0x218;
// PROC0_INTE..PROC1_INTE
pub fn IO_QSPI_PROC_INTE(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x21C + n * 0xC
}

// PROC0_INTF..PROC1_INTF
pub fn IO_QSPI_PROC_INTF(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x220 + n * 0xC
}

// PROC0_INTS..PROC1_INTS
pub fn IO_QSPI_PROC_INTS(n: u32) -> u32 {
    return IO_QSPI_BASE + 0x224 + n * 0xC
}

pub const IO_QSPI_DORMANT_WAKE_INTE:                u32 = IO_QSPI_BASE + 0x234;
pub const IO_QSPI_DORMANT_WAKE_INTF:                u32 = IO_QSPI_BASE + 0x238;
pub const IO_QSPI_DORMANT_WAKE_INTS:                u32 = IO_QSPI_BASE + 0x23C;
// ==== END AUTO-GENERATED REGISTER OFFSETS ====

// ==== BEGIN AUTO-GENERATED FIELD BIT RANGES (tools/gen_field_ranges.py) ====
// Generated from specs/RP2350.svd -- do not edit by hand.

// USBPHY_DP_STATUS, USBPHY_DM_STATUS, GPIO_QSPI_SCLK_STATUS, GPIO_QSPI_SS_STATUS, GPIO_QSPI_SD0_STATUS, GPIO_QSPI_SD1_STATUS, GPIO_QSPI_SD2_STATUS, GPIO_QSPI_SD3_STATUS
pub const IO_QSPI_STATUS_IRQTOPROC_BIT:             u32 = 26;
pub const IO_QSPI_STATUS_INFROMPAD_BIT:             u32 = 17;
pub const IO_QSPI_STATUS_OETOPAD_BIT:               u32 = 13;
pub const IO_QSPI_STATUS_OUTTOPAD_BIT:              u32 = 9;

// USBPHY_DP_CTRL, USBPHY_DM_CTRL, GPIO_QSPI_SCLK_CTRL, GPIO_QSPI_SS_CTRL, GPIO_QSPI_SD0_CTRL, GPIO_QSPI_SD1_CTRL, GPIO_QSPI_SD2_CTRL, GPIO_QSPI_SD3_CTRL
pub const IO_QSPI_CTRL_IRQOVER_LOW:                 u32 = 28;
pub const IO_QSPI_CTRL_IRQOVER_HIGH:                u32 = 29;
pub const IO_QSPI_CTRL_INOVER_LOW:                  u32 = 16;
pub const IO_QSPI_CTRL_INOVER_HIGH:                 u32 = 17;
pub const IO_QSPI_CTRL_OEOVER_LOW:                  u32 = 14;
pub const IO_QSPI_CTRL_OEOVER_HIGH:                 u32 = 15;
pub const IO_QSPI_CTRL_OUTOVER_LOW:                 u32 = 12;
pub const IO_QSPI_CTRL_OUTOVER_HIGH:                u32 = 13;
pub const IO_QSPI_CTRL_FUNCSEL_LOW:                 u32 = 0;
pub const IO_QSPI_CTRL_FUNCSEL_HIGH:                u32 = 4;

// IRQSUMMARY_PROC0_SECURE, IRQSUMMARY_PROC0_NONSECURE, IRQSUMMARY_PROC1_SECURE, IRQSUMMARY_PROC1_NONSECURE, IRQSUMMARY_DORMANT_WAKE_SECURE, IRQSUMMARY_DORMANT_WAKE_NONSECURE
pub const IO_QSPI_IRQSUMMARY_GPIO_QSPI_SD3_BIT:     u32 = 7;
pub const IO_QSPI_IRQSUMMARY_GPIO_QSPI_SD2_BIT:     u32 = 6;
pub const IO_QSPI_IRQSUMMARY_GPIO_QSPI_SD1_BIT:     u32 = 5;
pub const IO_QSPI_IRQSUMMARY_GPIO_QSPI_SD0_BIT:     u32 = 4;
pub const IO_QSPI_IRQSUMMARY_GPIO_QSPI_SS_BIT:      u32 = 3;
pub const IO_QSPI_IRQSUMMARY_GPIO_QSPI_SCLK_BIT:    u32 = 2;
pub const IO_QSPI_IRQSUMMARY_USBPHY_DM_BIT:         u32 = 1;
pub const IO_QSPI_IRQSUMMARY_USBPHY_DP_BIT:         u32 = 0;

// INTR
pub const IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_HIGH_BIT: u32 = 31;
pub const IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_HIGH_BIT: u32 = 27;
pub const IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_HIGH_BIT: u32 = 23;
pub const IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_HIGH_BIT: u32 = 19;
pub const IO_QSPI_INTR_GPIO_QSPI_SD3_EDGE_LOW_BIT:  u32 = 30;
pub const IO_QSPI_INTR_GPIO_QSPI_SD2_EDGE_LOW_BIT:  u32 = 26;
pub const IO_QSPI_INTR_GPIO_QSPI_SD1_EDGE_LOW_BIT:  u32 = 22;
pub const IO_QSPI_INTR_GPIO_QSPI_SD0_EDGE_LOW_BIT:  u32 = 18;
pub const IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 29;
pub const IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 25;
pub const IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_INTR_GPIO_QSPI_SD3_LEVEL_LOW_BIT: u32 = 28;
pub const IO_QSPI_INTR_GPIO_QSPI_SD2_LEVEL_LOW_BIT: u32 = 24;
pub const IO_QSPI_INTR_GPIO_QSPI_SD1_LEVEL_LOW_BIT: u32 = 20;
pub const IO_QSPI_INTR_GPIO_QSPI_SD0_LEVEL_LOW_BIT: u32 = 16;
pub const IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_HIGH_BIT:  u32 = 15;
pub const IO_QSPI_INTR_GPIO_QSPI_SS_EDGE_LOW_BIT:   u32 = 14;
pub const IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_HIGH_BIT: u32 = 13;
pub const IO_QSPI_INTR_GPIO_QSPI_SS_LEVEL_LOW_BIT:  u32 = 12;
pub const IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_INTR_GPIO_QSPI_SCLK_EDGE_LOW_BIT: u32 = 10;
pub const IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_INTR_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_INTR_USBPHY_DM_EDGE_HIGH_BIT:     u32 = 7;
pub const IO_QSPI_INTR_USBPHY_DM_EDGE_LOW_BIT:      u32 = 6;
pub const IO_QSPI_INTR_USBPHY_DM_LEVEL_HIGH_BIT:    u32 = 5;
pub const IO_QSPI_INTR_USBPHY_DM_LEVEL_LOW_BIT:     u32 = 4;
pub const IO_QSPI_INTR_USBPHY_DP_EDGE_HIGH_BIT:     u32 = 3;
pub const IO_QSPI_INTR_USBPHY_DP_EDGE_LOW_BIT:      u32 = 2;
pub const IO_QSPI_INTR_USBPHY_DP_LEVEL_HIGH_BIT:    u32 = 1;
pub const IO_QSPI_INTR_USBPHY_DP_LEVEL_LOW_BIT:     u32 = 0;

// PROC0_INTE, PROC1_INTE
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 31;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 27;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 30;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 26;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 29;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 25;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 28;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 24;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_PROC_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_PROC_INTE_USBPHY_DM_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_PROC_INTE_USBPHY_DM_EDGE_LOW_BIT: u32 = 6;
pub const IO_QSPI_PROC_INTE_USBPHY_DM_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_PROC_INTE_USBPHY_DM_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_PROC_INTE_USBPHY_DP_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_PROC_INTE_USBPHY_DP_EDGE_LOW_BIT: u32 = 2;
pub const IO_QSPI_PROC_INTE_USBPHY_DP_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_PROC_INTE_USBPHY_DP_LEVEL_LOW_BIT:u32 = 0;

// PROC0_INTF, PROC1_INTF
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 31;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 27;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 30;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 26;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 29;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 25;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 28;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 24;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_PROC_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_PROC_INTF_USBPHY_DM_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_PROC_INTF_USBPHY_DM_EDGE_LOW_BIT: u32 = 6;
pub const IO_QSPI_PROC_INTF_USBPHY_DM_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_PROC_INTF_USBPHY_DM_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_PROC_INTF_USBPHY_DP_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_PROC_INTF_USBPHY_DP_EDGE_LOW_BIT: u32 = 2;
pub const IO_QSPI_PROC_INTF_USBPHY_DP_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_PROC_INTF_USBPHY_DP_LEVEL_LOW_BIT:u32 = 0;

// PROC0_INTS, PROC1_INTS
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 31;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 27;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 30;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 26;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 29;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 25;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 28;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 24;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_PROC_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_PROC_INTS_USBPHY_DM_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_PROC_INTS_USBPHY_DM_EDGE_LOW_BIT: u32 = 6;
pub const IO_QSPI_PROC_INTS_USBPHY_DM_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_PROC_INTS_USBPHY_DM_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_PROC_INTS_USBPHY_DP_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_PROC_INTS_USBPHY_DP_EDGE_LOW_BIT: u32 = 2;
pub const IO_QSPI_PROC_INTS_USBPHY_DP_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_PROC_INTS_USBPHY_DP_LEVEL_LOW_BIT:u32 = 0;

// DORMANT_WAKE_INTE
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 31;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 27;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 30;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 26;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 29;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 25;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 28;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 24;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_DORMANT_WAKE_INTE_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_EDGE_LOW_BIT:u32 = 6;
pub const IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DM_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_EDGE_LOW_BIT:u32 = 2;
pub const IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_DORMANT_WAKE_INTE_USBPHY_DP_LEVEL_LOW_BIT:u32 = 0;

// DORMANT_WAKE_INTF
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 31;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 27;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 30;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 26;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 29;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 25;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 28;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 24;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_DORMANT_WAKE_INTF_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_EDGE_LOW_BIT:u32 = 6;
pub const IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DM_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_EDGE_LOW_BIT:u32 = 2;
pub const IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_DORMANT_WAKE_INTF_USBPHY_DP_LEVEL_LOW_BIT:u32 = 0;

// DORMANT_WAKE_INTS
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_HIGH_BIT:u32 = 31;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_HIGH_BIT:u32 = 27;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_HIGH_BIT:u32 = 23;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_HIGH_BIT:u32 = 19;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_EDGE_LOW_BIT:u32 = 30;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_EDGE_LOW_BIT:u32 = 26;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_EDGE_LOW_BIT:u32 = 22;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_EDGE_LOW_BIT:u32 = 18;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_HIGH_BIT:u32 = 29;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_HIGH_BIT:u32 = 25;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_HIGH_BIT:u32 = 21;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_HIGH_BIT:u32 = 17;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD3_LEVEL_LOW_BIT:u32 = 28;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD2_LEVEL_LOW_BIT:u32 = 24;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD1_LEVEL_LOW_BIT:u32 = 20;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SD0_LEVEL_LOW_BIT:u32 = 16;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_HIGH_BIT:u32 = 15;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_EDGE_LOW_BIT:u32 = 14;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_HIGH_BIT:u32 = 13;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SS_LEVEL_LOW_BIT:u32 = 12;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_HIGH_BIT:u32 = 11;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_EDGE_LOW_BIT:u32 = 10;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_HIGH_BIT:u32 = 9;
pub const IO_QSPI_DORMANT_WAKE_INTS_GPIO_QSPI_SCLK_LEVEL_LOW_BIT:u32 = 8;
pub const IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_EDGE_HIGH_BIT:u32 = 7;
pub const IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_EDGE_LOW_BIT:u32 = 6;
pub const IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_LEVEL_HIGH_BIT:u32 = 5;
pub const IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DM_LEVEL_LOW_BIT:u32 = 4;
pub const IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_EDGE_HIGH_BIT:u32 = 3;
pub const IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_EDGE_LOW_BIT:u32 = 2;
pub const IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_LEVEL_HIGH_BIT:u32 = 1;
pub const IO_QSPI_DORMANT_WAKE_INTS_USBPHY_DP_LEVEL_LOW_BIT:u32 = 0;
// ==== END AUTO-GENERATED FIELD BIT RANGES ====

// ==== BEGIN AUTO-GENERATED ENUMERATED VALUES (tools/gen_enum_values.py) ====
// Generated from specs/RP2350.svd -- do not edit by hand.

// USBPHY_DP_CTRL..GPIO_QSPI_SD3_CTRL: IRQOVER
pub const IO_QSPI_CTRL_IRQOVER_NORMAL:              u32 = 0x0;
pub const IO_QSPI_CTRL_IRQOVER_INVERT:              u32 = 0x1;
pub const IO_QSPI_CTRL_IRQOVER_LOW_1:               u32 = 0x2;
pub const IO_QSPI_CTRL_IRQOVER_HIGH_1:              u32 = 0x3;

// USBPHY_DP_CTRL..GPIO_QSPI_SD3_CTRL: INOVER
pub const IO_QSPI_CTRL_INOVER_NORMAL:               u32 = 0x0;
pub const IO_QSPI_CTRL_INOVER_INVERT:               u32 = 0x1;
pub const IO_QSPI_CTRL_INOVER_LOW_1:                u32 = 0x2;
pub const IO_QSPI_CTRL_INOVER_HIGH_1:               u32 = 0x3;

// USBPHY_DP_CTRL..GPIO_QSPI_SD3_CTRL: OEOVER
pub const IO_QSPI_CTRL_OEOVER_NORMAL:               u32 = 0x0;
pub const IO_QSPI_CTRL_OEOVER_INVERT:               u32 = 0x1;
pub const IO_QSPI_CTRL_OEOVER_DISABLE:              u32 = 0x2;
pub const IO_QSPI_CTRL_OEOVER_ENABLE:               u32 = 0x3;

// USBPHY_DP_CTRL..GPIO_QSPI_SD3_CTRL: OUTOVER
pub const IO_QSPI_CTRL_OUTOVER_NORMAL:              u32 = 0x0;
pub const IO_QSPI_CTRL_OUTOVER_INVERT:              u32 = 0x1;
pub const IO_QSPI_CTRL_OUTOVER_LOW_1:               u32 = 0x2;
pub const IO_QSPI_CTRL_OUTOVER_HIGH_1:              u32 = 0x3;

// USBPHY_DP_CTRL..GPIO_QSPI_SD1_CTRL: FUNCSEL
pub const IO_QSPI_CTRL_FUNCSEL_UART1_TX:            u32 = 0x2;
pub const IO_QSPI_CTRL_FUNCSEL_I2C0_SDA:            u32 = 0x3;
pub const IO_QSPI_CTRL_FUNCSEL_SIOB_PROC_56:        u32 = 0x5;
pub const IO_QSPI_CTRL_FUNCSEL_NULL:                u32 = 0x1F;
pub const IO_QSPI_CTRL_FUNCSEL_UART1_RX:            u32 = 0x2;
pub const IO_QSPI_CTRL_FUNCSEL_I2C0_SCL:            u32 = 0x3;
pub const IO_QSPI_CTRL_FUNCSEL_SIOB_PROC_57:        u32 = 0x5;
pub const IO_QSPI_CTRL_FUNCSEL_XIP_SD0:             u32 = 0x0;
pub const IO_QSPI_CTRL_FUNCSEL_UART0_TX:            u32 = 0x2;
pub const IO_QSPI_CTRL_FUNCSEL_SIOB_PROC_60:        u32 = 0x5;
pub const IO_QSPI_CTRL_FUNCSEL_XIP_SD1:             u32 = 0x0;
pub const IO_QSPI_CTRL_FUNCSEL_UART0_RX:            u32 = 0x2;
pub const IO_QSPI_CTRL_FUNCSEL_SIOB_PROC_61:        u32 = 0x5;

// GPIO_QSPI_SCLK_CTRL: FUNCSEL
pub const IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_XIP_SCLK:u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_UART1_CTS:u32 = 0x2;
pub const IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_I2C1_SDA:u32 = 0x3;
pub const IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_SIOB_PROC_58:u32 = 0x5;
pub const IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_UART1_TX:u32 = 0xB;
pub const IO_QSPI_GPIO_QSPI_SCLK_CTRL_FUNCSEL_NULL: u32 = 0x1F;

// GPIO_QSPI_SS_CTRL: FUNCSEL
pub const IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_XIP_SS_N_0:u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_UART1_RTS:u32 = 0x2;
pub const IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_I2C1_SCL:u32 = 0x3;
pub const IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_SIOB_PROC_59:u32 = 0x5;
pub const IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_UART1_RX:u32 = 0xB;
pub const IO_QSPI_GPIO_QSPI_SS_CTRL_FUNCSEL_NULL:   u32 = 0x1F;

// GPIO_QSPI_SD2_CTRL: FUNCSEL
pub const IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_XIP_SD2:u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_UART0_CTS:u32 = 0x2;
pub const IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_I2C1_SDA:u32 = 0x3;
pub const IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_SIOB_PROC_62:u32 = 0x5;
pub const IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_UART0_TX:u32 = 0xB;
pub const IO_QSPI_GPIO_QSPI_SD2_CTRL_FUNCSEL_NULL:  u32 = 0x1F;

// GPIO_QSPI_SD3_CTRL: FUNCSEL
pub const IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_XIP_SD3:u32 = 0x0;
pub const IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_UART0_RTS:u32 = 0x2;
pub const IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_I2C1_SCL:u32 = 0x3;
pub const IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_SIOB_PROC_63:u32 = 0x5;
pub const IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_UART0_RX:u32 = 0xB;
pub const IO_QSPI_GPIO_QSPI_SD3_CTRL_FUNCSEL_NULL:  u32 = 0x1F;
// ==== END AUTO-GENERATED ENUMERATED VALUES ====
