#![allow(dead_code)]
// OTP_DATA_RAW

// ==== BEGIN AUTO-GENERATED REGISTER OFFSETS (tools/gen_register_offsets.py) ====
// Generated from specs/RP2350.svd -- do not edit by hand.

pub const OTP_DATA_RAW_BASE:                        u32 = 0x4013_4000;

// CHIPID0..CHIPID3
pub fn OTP_DATA_RAW_CHIPID(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x0 + n * 0x4
}

// RANDID0..RANDID7
pub fn OTP_DATA_RAW_RANDID(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x10 + n * 0x4
}

pub const OTP_DATA_RAW_ROSC_CALIB:                  u32 = OTP_DATA_RAW_BASE + 0x40;
pub const OTP_DATA_RAW_LPOSC_CALIB:                 u32 = OTP_DATA_RAW_BASE + 0x44;
pub const OTP_DATA_RAW_NUM_GPIOS:                   u32 = OTP_DATA_RAW_BASE + 0x60;
// INFO_CRC0..INFO_CRC1
pub fn OTP_DATA_RAW_INFO_CRC(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0xD8 + n * 0x4
}

// CRIT0..CRIT1
pub fn OTP_DATA_RAW_CRIT(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0xE0 + n * 0x20
}

// CRIT0_R1..CRIT1_R1
pub fn OTP_DATA_RAW_CRIT_R1(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0xE4 + n * 0x20
}

// CRIT0_R2..CRIT1_R2
pub fn OTP_DATA_RAW_CRIT_R2(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0xE8 + n * 0x20
}

// CRIT0_R3..CRIT1_R3
pub fn OTP_DATA_RAW_CRIT_R3(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0xEC + n * 0x20
}

// CRIT0_R4..CRIT1_R4
pub fn OTP_DATA_RAW_CRIT_R4(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0xF0 + n * 0x20
}

// CRIT0_R5..CRIT1_R5
pub fn OTP_DATA_RAW_CRIT_R5(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0xF4 + n * 0x20
}

// CRIT0_R6..CRIT1_R6
pub fn OTP_DATA_RAW_CRIT_R6(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0xF8 + n * 0x20
}

// CRIT0_R7..CRIT1_R7
pub fn OTP_DATA_RAW_CRIT_R7(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0xFC + n * 0x20
}

// BOOT_FLAGS0..BOOT_FLAGS1
pub fn OTP_DATA_RAW_BOOT_FLAGS(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x120 + n * 0xC
}

// BOOT_FLAGS0_R1..BOOT_FLAGS1_R1
pub fn OTP_DATA_RAW_BOOT_FLAGS_R1(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x124 + n * 0xC
}

// BOOT_FLAGS0_R2..BOOT_FLAGS1_R2
pub fn OTP_DATA_RAW_BOOT_FLAGS_R2(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x128 + n * 0xC
}

// DEFAULT_BOOT_VERSION0..DEFAULT_BOOT_VERSION1
pub fn OTP_DATA_RAW_DEFAULT_BOOT_VERSION(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x138 + n * 0xC
}

// DEFAULT_BOOT_VERSION0_R1..DEFAULT_BOOT_VERSION1_R1
pub fn OTP_DATA_RAW_DEFAULT_BOOT_VERSION_R1(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x13C + n * 0xC
}

// DEFAULT_BOOT_VERSION0_R2..DEFAULT_BOOT_VERSION1_R2
pub fn OTP_DATA_RAW_DEFAULT_BOOT_VERSION_R2(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x140 + n * 0xC
}

pub const OTP_DATA_RAW_FLASH_DEVINFO:               u32 = OTP_DATA_RAW_BASE + 0x150;
pub const OTP_DATA_RAW_FLASH_PARTITION_SLOT_SIZE:   u32 = OTP_DATA_RAW_BASE + 0x154;
pub const OTP_DATA_RAW_BOOTSEL_LED_CFG:             u32 = OTP_DATA_RAW_BASE + 0x158;
pub const OTP_DATA_RAW_BOOTSEL_PLL_CFG:             u32 = OTP_DATA_RAW_BASE + 0x15C;
pub const OTP_DATA_RAW_BOOTSEL_XOSC_CFG:            u32 = OTP_DATA_RAW_BASE + 0x160;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS:              u32 = OTP_DATA_RAW_BASE + 0x164;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_R1:           u32 = OTP_DATA_RAW_BASE + 0x168;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_R2:           u32 = OTP_DATA_RAW_BASE + 0x16C;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR:        u32 = OTP_DATA_RAW_BASE + 0x170;
pub const OTP_DATA_RAW_OTPBOOT_SRC:                 u32 = OTP_DATA_RAW_BASE + 0x178;
pub const OTP_DATA_RAW_OTPBOOT_LEN:                 u32 = OTP_DATA_RAW_BASE + 0x17C;
// OTPBOOT_DST0..OTPBOOT_DST1
pub fn OTP_DATA_RAW_OTPBOOT_DST(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x180 + n * 0x4
}

// BOOTKEY0_0..BOOTKEY0_15
pub fn OTP_DATA_RAW_BOOTKEY0(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x200 + n * 0x4
}

// BOOTKEY1_0..BOOTKEY1_15
pub fn OTP_DATA_RAW_BOOTKEY1(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x240 + n * 0x4
}

// BOOTKEY2_0..BOOTKEY2_15
pub fn OTP_DATA_RAW_BOOTKEY2(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x280 + n * 0x4
}

// BOOTKEY3_0..BOOTKEY3_15
pub fn OTP_DATA_RAW_BOOTKEY3(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x2C0 + n * 0x4
}

// KEY1_0..KEY1_7
pub fn OTP_DATA_RAW_KEY1(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3D20 + n * 0x4
}

// KEY2_0..KEY2_7
pub fn OTP_DATA_RAW_KEY2(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3D40 + n * 0x4
}

// KEY3_0..KEY3_7
pub fn OTP_DATA_RAW_KEY3(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3D60 + n * 0x4
}

// KEY4_0..KEY4_7
pub fn OTP_DATA_RAW_KEY4(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3D80 + n * 0x4
}

// KEY5_0..KEY5_7
pub fn OTP_DATA_RAW_KEY5(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3DA0 + n * 0x4
}

// KEY6_0..KEY6_7
pub fn OTP_DATA_RAW_KEY6(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3DC0 + n * 0x4
}

pub const OTP_DATA_RAW_KEY1_VALID:                  u32 = OTP_DATA_RAW_BASE + 0x3DE4;
pub const OTP_DATA_RAW_KEY2_VALID:                  u32 = OTP_DATA_RAW_BASE + 0x3DE8;
pub const OTP_DATA_RAW_KEY3_VALID:                  u32 = OTP_DATA_RAW_BASE + 0x3DEC;
pub const OTP_DATA_RAW_KEY4_VALID:                  u32 = OTP_DATA_RAW_BASE + 0x3DF0;
pub const OTP_DATA_RAW_KEY5_VALID:                  u32 = OTP_DATA_RAW_BASE + 0x3DF4;
pub const OTP_DATA_RAW_KEY6_VALID:                  u32 = OTP_DATA_RAW_BASE + 0x3DF8;
// PAGE0_LOCK0..PAGE0_LOCK1
pub fn OTP_DATA_RAW_PAGE0_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E00 + n * 0x4
}

// PAGE1_LOCK0..PAGE1_LOCK1
pub fn OTP_DATA_RAW_PAGE1_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E08 + n * 0x4
}

// PAGE2_LOCK0..PAGE2_LOCK1
pub fn OTP_DATA_RAW_PAGE2_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E10 + n * 0x4
}

// PAGE3_LOCK0..PAGE3_LOCK1
pub fn OTP_DATA_RAW_PAGE3_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E18 + n * 0x4
}

// PAGE4_LOCK0..PAGE4_LOCK1
pub fn OTP_DATA_RAW_PAGE4_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E20 + n * 0x4
}

// PAGE5_LOCK0..PAGE5_LOCK1
pub fn OTP_DATA_RAW_PAGE5_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E28 + n * 0x4
}

// PAGE6_LOCK0..PAGE6_LOCK1
pub fn OTP_DATA_RAW_PAGE6_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E30 + n * 0x4
}

// PAGE7_LOCK0..PAGE7_LOCK1
pub fn OTP_DATA_RAW_PAGE7_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E38 + n * 0x4
}

// PAGE8_LOCK0..PAGE8_LOCK1
pub fn OTP_DATA_RAW_PAGE8_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E40 + n * 0x4
}

// PAGE9_LOCK0..PAGE9_LOCK1
pub fn OTP_DATA_RAW_PAGE9_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E48 + n * 0x4
}

// PAGE10_LOCK0..PAGE10_LOCK1
pub fn OTP_DATA_RAW_PAGE10_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E50 + n * 0x4
}

// PAGE11_LOCK0..PAGE11_LOCK1
pub fn OTP_DATA_RAW_PAGE11_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E58 + n * 0x4
}

// PAGE12_LOCK0..PAGE12_LOCK1
pub fn OTP_DATA_RAW_PAGE12_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E60 + n * 0x4
}

// PAGE13_LOCK0..PAGE13_LOCK1
pub fn OTP_DATA_RAW_PAGE13_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E68 + n * 0x4
}

// PAGE14_LOCK0..PAGE14_LOCK1
pub fn OTP_DATA_RAW_PAGE14_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E70 + n * 0x4
}

// PAGE15_LOCK0..PAGE15_LOCK1
pub fn OTP_DATA_RAW_PAGE15_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E78 + n * 0x4
}

// PAGE16_LOCK0..PAGE16_LOCK1
pub fn OTP_DATA_RAW_PAGE16_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E80 + n * 0x4
}

// PAGE17_LOCK0..PAGE17_LOCK1
pub fn OTP_DATA_RAW_PAGE17_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E88 + n * 0x4
}

// PAGE18_LOCK0..PAGE18_LOCK1
pub fn OTP_DATA_RAW_PAGE18_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E90 + n * 0x4
}

// PAGE19_LOCK0..PAGE19_LOCK1
pub fn OTP_DATA_RAW_PAGE19_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3E98 + n * 0x4
}

// PAGE20_LOCK0..PAGE20_LOCK1
pub fn OTP_DATA_RAW_PAGE20_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3EA0 + n * 0x4
}

// PAGE21_LOCK0..PAGE21_LOCK1
pub fn OTP_DATA_RAW_PAGE21_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3EA8 + n * 0x4
}

// PAGE22_LOCK0..PAGE22_LOCK1
pub fn OTP_DATA_RAW_PAGE22_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3EB0 + n * 0x4
}

// PAGE23_LOCK0..PAGE23_LOCK1
pub fn OTP_DATA_RAW_PAGE23_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3EB8 + n * 0x4
}

// PAGE24_LOCK0..PAGE24_LOCK1
pub fn OTP_DATA_RAW_PAGE24_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3EC0 + n * 0x4
}

// PAGE25_LOCK0..PAGE25_LOCK1
pub fn OTP_DATA_RAW_PAGE25_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3EC8 + n * 0x4
}

// PAGE26_LOCK0..PAGE26_LOCK1
pub fn OTP_DATA_RAW_PAGE26_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3ED0 + n * 0x4
}

// PAGE27_LOCK0..PAGE27_LOCK1
pub fn OTP_DATA_RAW_PAGE27_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3ED8 + n * 0x4
}

// PAGE28_LOCK0..PAGE28_LOCK1
pub fn OTP_DATA_RAW_PAGE28_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3EE0 + n * 0x4
}

// PAGE29_LOCK0..PAGE29_LOCK1
pub fn OTP_DATA_RAW_PAGE29_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3EE8 + n * 0x4
}

// PAGE30_LOCK0..PAGE30_LOCK1
pub fn OTP_DATA_RAW_PAGE30_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3EF0 + n * 0x4
}

// PAGE31_LOCK0..PAGE31_LOCK1
pub fn OTP_DATA_RAW_PAGE31_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3EF8 + n * 0x4
}

// PAGE32_LOCK0..PAGE32_LOCK1
pub fn OTP_DATA_RAW_PAGE32_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F00 + n * 0x4
}

// PAGE33_LOCK0..PAGE33_LOCK1
pub fn OTP_DATA_RAW_PAGE33_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F08 + n * 0x4
}

// PAGE34_LOCK0..PAGE34_LOCK1
pub fn OTP_DATA_RAW_PAGE34_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F10 + n * 0x4
}

// PAGE35_LOCK0..PAGE35_LOCK1
pub fn OTP_DATA_RAW_PAGE35_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F18 + n * 0x4
}

// PAGE36_LOCK0..PAGE36_LOCK1
pub fn OTP_DATA_RAW_PAGE36_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F20 + n * 0x4
}

// PAGE37_LOCK0..PAGE37_LOCK1
pub fn OTP_DATA_RAW_PAGE37_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F28 + n * 0x4
}

// PAGE38_LOCK0..PAGE38_LOCK1
pub fn OTP_DATA_RAW_PAGE38_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F30 + n * 0x4
}

// PAGE39_LOCK0..PAGE39_LOCK1
pub fn OTP_DATA_RAW_PAGE39_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F38 + n * 0x4
}

// PAGE40_LOCK0..PAGE40_LOCK1
pub fn OTP_DATA_RAW_PAGE40_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F40 + n * 0x4
}

// PAGE41_LOCK0..PAGE41_LOCK1
pub fn OTP_DATA_RAW_PAGE41_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F48 + n * 0x4
}

// PAGE42_LOCK0..PAGE42_LOCK1
pub fn OTP_DATA_RAW_PAGE42_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F50 + n * 0x4
}

// PAGE43_LOCK0..PAGE43_LOCK1
pub fn OTP_DATA_RAW_PAGE43_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F58 + n * 0x4
}

// PAGE44_LOCK0..PAGE44_LOCK1
pub fn OTP_DATA_RAW_PAGE44_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F60 + n * 0x4
}

// PAGE45_LOCK0..PAGE45_LOCK1
pub fn OTP_DATA_RAW_PAGE45_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F68 + n * 0x4
}

// PAGE46_LOCK0..PAGE46_LOCK1
pub fn OTP_DATA_RAW_PAGE46_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F70 + n * 0x4
}

// PAGE47_LOCK0..PAGE47_LOCK1
pub fn OTP_DATA_RAW_PAGE47_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F78 + n * 0x4
}

// PAGE48_LOCK0..PAGE48_LOCK1
pub fn OTP_DATA_RAW_PAGE48_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F80 + n * 0x4
}

// PAGE49_LOCK0..PAGE49_LOCK1
pub fn OTP_DATA_RAW_PAGE49_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F88 + n * 0x4
}

// PAGE50_LOCK0..PAGE50_LOCK1
pub fn OTP_DATA_RAW_PAGE50_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F90 + n * 0x4
}

// PAGE51_LOCK0..PAGE51_LOCK1
pub fn OTP_DATA_RAW_PAGE51_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3F98 + n * 0x4
}

// PAGE52_LOCK0..PAGE52_LOCK1
pub fn OTP_DATA_RAW_PAGE52_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FA0 + n * 0x4
}

// PAGE53_LOCK0..PAGE53_LOCK1
pub fn OTP_DATA_RAW_PAGE53_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FA8 + n * 0x4
}

// PAGE54_LOCK0..PAGE54_LOCK1
pub fn OTP_DATA_RAW_PAGE54_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FB0 + n * 0x4
}

// PAGE55_LOCK0..PAGE55_LOCK1
pub fn OTP_DATA_RAW_PAGE55_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FB8 + n * 0x4
}

// PAGE56_LOCK0..PAGE56_LOCK1
pub fn OTP_DATA_RAW_PAGE56_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FC0 + n * 0x4
}

// PAGE57_LOCK0..PAGE57_LOCK1
pub fn OTP_DATA_RAW_PAGE57_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FC8 + n * 0x4
}

// PAGE58_LOCK0..PAGE58_LOCK1
pub fn OTP_DATA_RAW_PAGE58_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FD0 + n * 0x4
}

// PAGE59_LOCK0..PAGE59_LOCK1
pub fn OTP_DATA_RAW_PAGE59_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FD8 + n * 0x4
}

// PAGE60_LOCK0..PAGE60_LOCK1
pub fn OTP_DATA_RAW_PAGE60_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FE0 + n * 0x4
}

// PAGE61_LOCK0..PAGE61_LOCK1
pub fn OTP_DATA_RAW_PAGE61_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FE8 + n * 0x4
}

// PAGE62_LOCK0..PAGE62_LOCK1
pub fn OTP_DATA_RAW_PAGE62_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FF0 + n * 0x4
}

// PAGE63_LOCK0..PAGE63_LOCK1
pub fn OTP_DATA_RAW_PAGE63_LOCK(n: u32) -> u32 {
    return OTP_DATA_RAW_BASE + 0x3FF8 + n * 0x4
}
// ==== END AUTO-GENERATED REGISTER OFFSETS ====

// ==== BEGIN AUTO-GENERATED FIELD BIT RANGES (tools/gen_field_ranges.py) ====
// Generated from specs/RP2350.svd -- do not edit by hand.

// CHIPID0, CHIPID1, CHIPID2, CHIPID3
pub const OTP_DATA_RAW_CHIPID_LOW:                  u32 = 0;
pub const OTP_DATA_RAW_CHIPID_HIGH:                 u32 = 15;

// RANDID0, RANDID1, RANDID2, RANDID3, RANDID4, RANDID5, RANDID6, RANDID7
pub const OTP_DATA_RAW_RANDID_LOW:                  u32 = 0;
pub const OTP_DATA_RAW_RANDID_HIGH:                 u32 = 15;

// ROSC_CALIB
pub const OTP_DATA_RAW_ROSC_CALIB_LOW:              u32 = 0;
pub const OTP_DATA_RAW_ROSC_CALIB_HIGH:             u32 = 15;

// LPOSC_CALIB
pub const OTP_DATA_RAW_LPOSC_CALIB_LOW:             u32 = 0;
pub const OTP_DATA_RAW_LPOSC_CALIB_HIGH:            u32 = 15;

// NUM_GPIOS
pub const OTP_DATA_RAW_NUM_GPIOS_LOW:               u32 = 0;
pub const OTP_DATA_RAW_NUM_GPIOS_HIGH:              u32 = 7;

// INFO_CRC0, INFO_CRC1
pub const OTP_DATA_RAW_INFO_CRC_LOW:                u32 = 0;
pub const OTP_DATA_RAW_INFO_CRC_HIGH:               u32 = 15;

// CRIT0
pub const OTP_DATA_RAW_CRIT0_RISCV_DISABLE_BIT:     u32 = 1;
pub const OTP_DATA_RAW_CRIT0_ARM_DISABLE_BIT:       u32 = 0;

// CRIT0_R1..CRIT1_R7
pub const OTP_DATA_RAW_CRIT_R_LOW:                  u32 = 0;
pub const OTP_DATA_RAW_CRIT_R_HIGH:                 u32 = 23;

// CRIT1
pub const OTP_DATA_RAW_CRIT1_GLITCH_DETECTOR_SENS_LOW:u32 = 5;
pub const OTP_DATA_RAW_CRIT1_GLITCH_DETECTOR_SENS_HIGH:u32 = 6;
pub const OTP_DATA_RAW_CRIT1_GLITCH_DETECTOR_ENABLE_BIT:u32 = 4;
pub const OTP_DATA_RAW_CRIT1_BOOT_ARCH_BIT:         u32 = 3;
pub const OTP_DATA_RAW_CRIT1_DEBUG_DISABLE_BIT:     u32 = 2;
pub const OTP_DATA_RAW_CRIT1_SECURE_DEBUG_DISABLE_BIT:u32 = 1;
pub const OTP_DATA_RAW_CRIT1_SECURE_BOOT_ENABLE_BIT:u32 = 0;

// BOOT_FLAGS0
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_SRAM_WINDOW_BOOT_BIT:u32 = 21;
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_XIP_ACCESS_ON_SRAM_ENTRY_BIT:u32 = 20;
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_BOOTSEL_UART_BOOT_BIT:u32 = 19;
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_BOOTSEL_USB_PICOBOOT_IFC_BIT:u32 = 18;
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_BOOTSEL_USB_MSD_IFC_BIT:u32 = 17;
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_WATCHDOG_SCRATCH_BIT:u32 = 16;
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_POWER_SCRATCH_BIT:u32 = 15;
pub const OTP_DATA_RAW_BOOT_FLAGS0_ENABLE_OTP_BOOT_BIT:u32 = 14;
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_OTP_BOOT_BIT:u32 = 13;
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_FLASH_BOOT_BIT:u32 = 12;
pub const OTP_DATA_RAW_BOOT_FLAGS0_ROLLBACK_REQUIRED_BIT:u32 = 11;
pub const OTP_DATA_RAW_BOOT_FLAGS0_HASHED_PARTITION_TABLE_BIT:u32 = 10;
pub const OTP_DATA_RAW_BOOT_FLAGS0_SECURE_PARTITION_TABLE_BIT:u32 = 9;
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_AUTO_SWITCH_ARCH_BIT:u32 = 8;
pub const OTP_DATA_RAW_BOOT_FLAGS0_SINGLE_FLASH_BINARY_BIT:u32 = 7;
pub const OTP_DATA_RAW_BOOT_FLAGS0_OVERRIDE_FLASH_PARTITION_SLOT_SIZE_BIT:u32 = 6;
pub const OTP_DATA_RAW_BOOT_FLAGS0_FLASH_DEVINFO_ENABLE_BIT:u32 = 5;
pub const OTP_DATA_RAW_BOOT_FLAGS0_FAST_SIGCHECK_ROSC_DIV_BIT:u32 = 4;
pub const OTP_DATA_RAW_BOOT_FLAGS0_FLASH_IO_VOLTAGE_1V8_BIT:u32 = 3;
pub const OTP_DATA_RAW_BOOT_FLAGS0_ENABLE_BOOTSEL_NON_DEFAULT_PLL_XOSC_CFG_BIT:u32 = 2;
pub const OTP_DATA_RAW_BOOT_FLAGS0_ENABLE_BOOTSEL_LED_BIT:u32 = 1;
pub const OTP_DATA_RAW_BOOT_FLAGS0_DISABLE_BOOTSEL_EXEC2_BIT:u32 = 0;

// BOOT_FLAGS0_R1, BOOT_FLAGS0_R2, BOOT_FLAGS1_R1, BOOT_FLAGS1_R2
pub const OTP_DATA_RAW_BOOT_FLAGS_R_LOW:            u32 = 0;
pub const OTP_DATA_RAW_BOOT_FLAGS_R_HIGH:           u32 = 23;

// BOOT_FLAGS1
pub const OTP_DATA_RAW_BOOT_FLAGS1_DOUBLE_TAP_BIT:  u32 = 19;
pub const OTP_DATA_RAW_BOOT_FLAGS1_DOUBLE_TAP_DELAY_LOW:u32 = 16;
pub const OTP_DATA_RAW_BOOT_FLAGS1_DOUBLE_TAP_DELAY_HIGH:u32 = 18;
pub const OTP_DATA_RAW_BOOT_FLAGS1_KEY_INVALID_LOW: u32 = 8;
pub const OTP_DATA_RAW_BOOT_FLAGS1_KEY_INVALID_HIGH:u32 = 11;
pub const OTP_DATA_RAW_BOOT_FLAGS1_KEY_VALID_LOW:   u32 = 0;
pub const OTP_DATA_RAW_BOOT_FLAGS1_KEY_VALID_HIGH:  u32 = 3;

// DEFAULT_BOOT_VERSION0, DEFAULT_BOOT_VERSION1
pub const OTP_DATA_RAW_DEFAULT_BOOT_VERSION_LOW:    u32 = 0;
pub const OTP_DATA_RAW_DEFAULT_BOOT_VERSION_HIGH:   u32 = 23;

// DEFAULT_BOOT_VERSION0_R1, DEFAULT_BOOT_VERSION0_R2, DEFAULT_BOOT_VERSION1_R1, DEFAULT_BOOT_VERSION1_R2
pub const OTP_DATA_RAW_DEFAULT_BOOT_VERSION_R_LOW:  u32 = 0;
pub const OTP_DATA_RAW_DEFAULT_BOOT_VERSION_R_HIGH: u32 = 23;

// FLASH_DEVINFO
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS1_SIZE_LOW:  u32 = 12;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS1_SIZE_HIGH: u32 = 15;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS0_SIZE_LOW:  u32 = 8;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS0_SIZE_HIGH: u32 = 11;
pub const OTP_DATA_RAW_FLASH_DEVINFO_D8H_ERASE_SUPPORTED_BIT:u32 = 7;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS1_GPIO_LOW:  u32 = 0;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS1_GPIO_HIGH: u32 = 5;

// FLASH_PARTITION_SLOT_SIZE
pub const OTP_DATA_RAW_FLASH_PARTITION_SLOT_SIZE_LOW:u32 = 0;
pub const OTP_DATA_RAW_FLASH_PARTITION_SLOT_SIZE_HIGH:u32 = 15;

// BOOTSEL_LED_CFG
pub const OTP_DATA_RAW_BOOTSEL_LED_CFG_ACTIVELOW_BIT:u32 = 8;
pub const OTP_DATA_RAW_BOOTSEL_LED_CFG_PIN_LOW:     u32 = 0;
pub const OTP_DATA_RAW_BOOTSEL_LED_CFG_PIN_HIGH:    u32 = 5;

// BOOTSEL_PLL_CFG
pub const OTP_DATA_RAW_BOOTSEL_PLL_CFG_REFDIV_BIT:  u32 = 15;
pub const OTP_DATA_RAW_BOOTSEL_PLL_CFG_POSTDIV2_LOW:u32 = 12;
pub const OTP_DATA_RAW_BOOTSEL_PLL_CFG_POSTDIV2_HIGH:u32 = 14;
pub const OTP_DATA_RAW_BOOTSEL_PLL_CFG_POSTDIV1_LOW:u32 = 9;
pub const OTP_DATA_RAW_BOOTSEL_PLL_CFG_POSTDIV1_HIGH:u32 = 11;
pub const OTP_DATA_RAW_BOOTSEL_PLL_CFG_FBDIV_LOW:   u32 = 0;
pub const OTP_DATA_RAW_BOOTSEL_PLL_CFG_FBDIV_HIGH:  u32 = 8;

// BOOTSEL_XOSC_CFG
pub const OTP_DATA_RAW_BOOTSEL_XOSC_CFG_RANGE_LOW:  u32 = 14;
pub const OTP_DATA_RAW_BOOTSEL_XOSC_CFG_RANGE_HIGH: u32 = 15;
pub const OTP_DATA_RAW_BOOTSEL_XOSC_CFG_STARTUP_LOW:u32 = 0;
pub const OTP_DATA_RAW_BOOTSEL_XOSC_CFG_STARTUP_HIGH:u32 = 13;

// USB_BOOT_FLAGS
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_DP_DM_SWAP_BIT:u32 = 23;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WHITE_LABEL_ADDR_VALID_BIT:u32 = 22;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_INFO_UF2_TXT_BOARD_ID_STRDEF_VALID_BIT:u32 = 15;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_INFO_UF2_TXT_MODEL_STRDEF_VALID_BIT:u32 = 14;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_INDEX_HTM_REDIRECT_NAME_STRDEF_VALID_BIT:u32 = 13;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_INDEX_HTM_REDIRECT_URL_STRDEF_VALID_BIT:u32 = 12;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_SCSI_INQUIRY_VERSION_STRDEF_VALID_BIT:u32 = 11;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_SCSI_INQUIRY_PRODUCT_STRDEF_VALID_BIT:u32 = 10;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_SCSI_INQUIRY_VENDOR_STRDEF_VALID_BIT:u32 = 9;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_VOLUME_LABEL_STRDEF_VALID_BIT:u32 = 8;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_USB_CONFIG_ATTRIBUTES_MAX_POWER_VALUES_VALID_BIT:u32 = 7;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_USB_DEVICE_SERIAL_NUMBER_STRDEF_VALID_BIT:u32 = 6;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_USB_DEVICE_PRODUCT_STRDEF_VALID_BIT:u32 = 5;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_USB_DEVICE_MANUFACTURER_STRDEF_VALID_BIT:u32 = 4;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_USB_DEVICE_LANG_ID_VALUE_VALID_BIT:u32 = 3;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_USB_DEVICE_SERIAL_NUMBER_VALUE_VALID_BIT:u32 = 2;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_USB_DEVICE_PID_VALUE_VALID_BIT:u32 = 1;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_WL_USB_DEVICE_VID_VALUE_VALID_BIT:u32 = 0;

// USB_BOOT_FLAGS_R1, USB_BOOT_FLAGS_R2
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_R_LOW:        u32 = 0;
pub const OTP_DATA_RAW_USB_BOOT_FLAGS_R_HIGH:       u32 = 23;

// USB_WHITE_LABEL_ADDR
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_LOW:    u32 = 0;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_HIGH:   u32 = 15;

// OTPBOOT_SRC
pub const OTP_DATA_RAW_OTPBOOT_SRC_LOW:             u32 = 0;
pub const OTP_DATA_RAW_OTPBOOT_SRC_HIGH:            u32 = 15;

// OTPBOOT_LEN
pub const OTP_DATA_RAW_OTPBOOT_LEN_LOW:             u32 = 0;
pub const OTP_DATA_RAW_OTPBOOT_LEN_HIGH:            u32 = 15;

// OTPBOOT_DST0, OTPBOOT_DST1
pub const OTP_DATA_RAW_OTPBOOT_DST_LOW:             u32 = 0;
pub const OTP_DATA_RAW_OTPBOOT_DST_HIGH:            u32 = 15;

// BOOTKEY0_0..BOOTKEY3_15
pub const OTP_DATA_RAW_BOOTKEY_LOW:                 u32 = 0;
pub const OTP_DATA_RAW_BOOTKEY_HIGH:                u32 = 15;

// KEY1_0..KEY6_7
pub const OTP_DATA_RAW_KEY_LOW:                     u32 = 0;
pub const OTP_DATA_RAW_KEY_HIGH:                    u32 = 15;

// KEY1_VALID, KEY2_VALID, KEY3_VALID, KEY4_VALID, KEY5_VALID, KEY6_VALID
pub const OTP_DATA_RAW_KEY_VALID_VALID_R2_BIT:      u32 = 16;
pub const OTP_DATA_RAW_KEY_VALID_VALID_R1_BIT:      u32 = 8;
pub const OTP_DATA_RAW_KEY_VALID_VALID_BIT:         u32 = 0;

// PAGE0_LOCK0..PAGE62_LOCK0
pub const OTP_DATA_RAW_PAGE_LOCK_R2_LOW:            u32 = 16;
pub const OTP_DATA_RAW_PAGE_LOCK_R2_HIGH:           u32 = 23;
pub const OTP_DATA_RAW_PAGE_LOCK_R1_LOW:            u32 = 8;
pub const OTP_DATA_RAW_PAGE_LOCK_R1_HIGH:           u32 = 15;
pub const OTP_DATA_RAW_PAGE_LOCK_NO_KEY_STATE_BIT:  u32 = 6;
pub const OTP_DATA_RAW_PAGE_LOCK_KEY_R_LOW:         u32 = 3;
pub const OTP_DATA_RAW_PAGE_LOCK_KEY_R_HIGH:        u32 = 5;
pub const OTP_DATA_RAW_PAGE_LOCK_KEY_W_LOW:         u32 = 0;
pub const OTP_DATA_RAW_PAGE_LOCK_KEY_W_HIGH:        u32 = 2;

// PAGE0_LOCK1..PAGE63_LOCK1
pub const OTP_DATA_RAW_PAGE0_LOCK1_R2_LOW:          u32 = 16;
pub const OTP_DATA_RAW_PAGE0_LOCK1_R2_HIGH:         u32 = 23;
pub const OTP_DATA_RAW_PAGE0_LOCK1_R1_LOW:          u32 = 8;
pub const OTP_DATA_RAW_PAGE0_LOCK1_R1_HIGH:         u32 = 15;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_BL_LOW:     u32 = 4;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_BL_HIGH:    u32 = 5;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_NS_LOW:     u32 = 2;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_NS_HIGH:    u32 = 3;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_S_LOW:      u32 = 0;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_S_HIGH:     u32 = 1;

// PAGE63_LOCK0
pub const OTP_DATA_RAW_PAGE63_LOCK0_R2_LOW:         u32 = 16;
pub const OTP_DATA_RAW_PAGE63_LOCK0_R2_HIGH:        u32 = 23;
pub const OTP_DATA_RAW_PAGE63_LOCK0_R1_LOW:         u32 = 8;
pub const OTP_DATA_RAW_PAGE63_LOCK0_R1_HIGH:        u32 = 15;
pub const OTP_DATA_RAW_PAGE63_LOCK0_RMA_BIT:        u32 = 7;
pub const OTP_DATA_RAW_PAGE63_LOCK0_NO_KEY_STATE_BIT:u32 = 6;
pub const OTP_DATA_RAW_PAGE63_LOCK0_KEY_R_LOW:      u32 = 3;
pub const OTP_DATA_RAW_PAGE63_LOCK0_KEY_R_HIGH:     u32 = 5;
pub const OTP_DATA_RAW_PAGE63_LOCK0_KEY_W_LOW:      u32 = 0;
pub const OTP_DATA_RAW_PAGE63_LOCK0_KEY_W_HIGH:     u32 = 2;
// ==== END AUTO-GENERATED FIELD BIT RANGES ====

// ==== BEGIN AUTO-GENERATED ENUMERATED VALUES (tools/gen_enum_values.py) ====
// Generated from specs/RP2350.svd -- do not edit by hand.

// FLASH_DEVINFO..FLASH_DEVINFO: CS_SIZE
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_NONE:  u32 = 0x0;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_8K:    u32 = 0x1;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_16K:   u32 = 0x2;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_32K:   u32 = 0x3;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_64K:   u32 = 0x4;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_128K:  u32 = 0x5;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_256K:  u32 = 0x6;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_512K:  u32 = 0x7;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_1M:    u32 = 0x8;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_2M:    u32 = 0x9;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_4M:    u32 = 0xA;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_8M:    u32 = 0xB;
pub const OTP_DATA_RAW_FLASH_DEVINFO_CS_SIZE_16M:   u32 = 0xC;

// BOOTSEL_XOSC_CFG: RANGE
pub const OTP_DATA_RAW_BOOTSEL_XOSC_CFG_RANGE_1_15MHZ:u32 = 0x0;
pub const OTP_DATA_RAW_BOOTSEL_XOSC_CFG_RANGE_10_30MHZ:u32 = 0x1;
pub const OTP_DATA_RAW_BOOTSEL_XOSC_CFG_RANGE_25_60MHZ:u32 = 0x2;
pub const OTP_DATA_RAW_BOOTSEL_XOSC_CFG_RANGE_40_100MHZ:u32 = 0x3;

// USB_WHITE_LABEL_ADDR: USB_WHITE_LABEL_ADDR
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_USB_DEVICE_VID_VALUE:u32 = 0x0;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_USB_DEVICE_PID_VALUE:u32 = 0x1;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_USB_DEVICE_BCD_DEVICE_VALUE:u32 = 0x2;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_USB_DEVICE_LANG_ID_VALUE:u32 = 0x3;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_USB_DEVICE_MANUFACTURER_STRDEF:u32 = 0x4;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_USB_DEVICE_PRODUCT_STRDEF:u32 = 0x5;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_USB_DEVICE_SERIAL_NUMBER_STRDEF:u32 = 0x6;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_USB_CONFIG_ATTRIBUTES_MAX_POWER_VALUES:u32 = 0x7;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_VOLUME_LABEL_STRDEF:u32 = 0x8;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_SCSI_INQUIRY_VENDOR_STRDEF:u32 = 0x9;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_SCSI_INQUIRY_PRODUCT_STRDEF:u32 = 0xA;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_SCSI_INQUIRY_VERSION_STRDEF:u32 = 0xB;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_INDEX_HTM_REDIRECT_URL_STRDEF:u32 = 0xC;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_INDEX_HTM_REDIRECT_NAME_STRDEF:u32 = 0xD;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_INFO_UF2_TXT_MODEL_STRDEF:u32 = 0xE;
pub const OTP_DATA_RAW_USB_WHITE_LABEL_ADDR_INDEX_INFO_UF2_TXT_BOARD_ID_STRDEF:u32 = 0xF;

// PAGE0_LOCK0..PAGE62_LOCK0: NO_KEY_STATE
pub const OTP_DATA_RAW_PAGE_LOCK_NO_KEY_STATE_READ_ONLY:u32 = 0x0;
pub const OTP_DATA_RAW_PAGE_LOCK_NO_KEY_STATE_INACCESSIBLE:u32 = 0x1;

// PAGE0_LOCK1..PAGE63_LOCK1: LOCK_BL
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_BL_READ_WRITE:u32 = 0x0;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_BL_READ_ONLY:u32 = 0x1;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_BL_RESERVED:u32 = 0x2;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_BL_INACCESSIBLE:u32 = 0x3;

// PAGE0_LOCK1..PAGE63_LOCK1: LOCK_NS
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_NS_READ_WRITE:u32 = 0x0;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_NS_READ_ONLY:u32 = 0x1;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_NS_RESERVED:u32 = 0x2;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_NS_INACCESSIBLE:u32 = 0x3;

// PAGE0_LOCK1..PAGE63_LOCK1: LOCK_S
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_S_READ_WRITE:u32 = 0x0;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_S_READ_ONLY:u32 = 0x1;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_S_RESERVED: u32 = 0x2;
pub const OTP_DATA_RAW_PAGE0_LOCK1_LOCK_S_INACCESSIBLE:u32 = 0x3;

// PAGE63_LOCK0: NO_KEY_STATE
pub const OTP_DATA_RAW_PAGE63_LOCK0_NO_KEY_STATE_READ_ONLY:u32 = 0x0;
pub const OTP_DATA_RAW_PAGE63_LOCK0_NO_KEY_STATE_INACCESSIBLE:u32 = 0x1;
// ==== END AUTO-GENERATED ENUMERATED VALUES ====
